name: setup node
description: setup node 22, restore npm cache, run npm ci

runs:
    using: composite
    steps:
        - uses: actions/setup-node@v6
          with:
              node-version: 22
              cache: npm

        - name: install dependencies
          run: npm ci
          shell: bash
