export const ADV_PREFIX_ACCOUNT_SIGNATURE: Readonly<Uint8Array> = new Uint8Array([6, 0])
export const ADV_PREFIX_DEVICE_SIGNATURE: Readonly<Uint8Array> = new Uint8Array([6, 1])
export const ADV_PREFIX_ACCOUNT_KEY_INDEX: Readonly<Uint8Array> = new Uint8Array([6, 2])
export const ADV_PREFIX_HOSTED_ACCOUNT_SIGNATURE: Readonly<Uint8Array> = new Uint8Array([6, 5])
export const ADV_PREFIX_HOSTED_DEVICE_SIGNATURE: Readonly<Uint8Array> = new Uint8Array([6, 6])
export const ADV_PREFIX_HOSTED_ACCOUNT_KEY_INDEX: Readonly<Uint8Array> = new Uint8Array([6, 7])
